[package]
name = "split_by_discriminant_macros"
version = "0.1.1"
edition = "2024"
authors = ["Dave Lee <dave@gray101.com>"]
license = "MIT"
description = "proc_macros intended for use with split_by_discriminant"
repository = "https://github.com/dave-gray101/split_by_discriminant"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.117", features = ["full"] }
quote = "1"
proc-macro2 = "1"
split_by_discriminant = { path = "../", version = "0.5.1", features = ["proc_macro"] }